export const apiProducts = [
  {
    id: 311787,
    is_dead: false,
    name: "Budweiser",
    tags: "budweiser beer lager canada ontario labatt breweries can",
    is_discontinued: false,
    price_in_cents: 1495,
    regular_price_in_cents: 1495,
    limited_time_offer_savings_in_cents: 0,
    limited_time_offer_ends_on: null,
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Canada, Ontario",
    product_package: "6x473 mL can",
    package_unit_type: "can",
    package_unit_volume_in_milliliters: 473,
    total_package_units: 6,
    volume_in_milliliters: 2838,
    alcohol_content: 500,
    price_per_liter_of_alcohol_in_cents: 1053,
    price_per_liter_in_cents: 526,
    inventory_count: 49240,
    inventory_volume_in_milliliters: 139743120,
    inventory_price_in_cents: 73613800,
    sugar_content: null,
    producer_name: "Labatt Breweries Ontario",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: false,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion: "Serve ice cold with finger foods and bar snacks.",
    tasting_note:
      "Light golden colour; light malt & hops; light body, touch of citrus to finish",
    updated_at: "2019-01-21T14:19:36.585Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/311787/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/311787/images/full.jpeg",
    varietal: "North American Lager",
    style: "Light & Malty",
    tertiary_category: "Pale Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 311787
  },
  {
    id: 300681,
    is_dead: false,
    name: "Coors Light",
    tags:
      "coors light beer lager canada ontario molson's molsons brewery of limited can",
    is_discontinued: false,
    price_in_cents: 1495,
    regular_price_in_cents: 1495,
    limited_time_offer_savings_in_cents: 0,
    limited_time_offer_ends_on: null,
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Canada, Ontario",
    product_package: "6x473 mL can",
    package_unit_type: "can",
    package_unit_volume_in_milliliters: 473,
    total_package_units: 6,
    volume_in_milliliters: 2838,
    alcohol_content: 400,
    price_per_liter_of_alcohol_in_cents: 1316,
    price_per_liter_in_cents: 526,
    inventory_count: 45694,
    inventory_volume_in_milliliters: 129679572,
    inventory_price_in_cents: 68312530,
    sugar_content: null,
    producer_name: "Molson's Brewery of Canada Limited",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: false,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion: "serve chilled with finger foods",
    tasting_note:
      "Pale gold colour; light grain with a touch of mineral aroma and flavour; soft, pleasant finish.",
    updated_at: "2019-01-21T14:23:05.731Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/300681/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/300681/images/full.jpeg",
    varietal: "Light Lager",
    style: "Light & Malty",
    tertiary_category: "Light Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 300681
  },
  {
    id: 300699,
    is_dead: false,
    name: "Molson Canadian",
    tags:
      "molson canadian beer lager canada ontario molson's molsons brewery of limited can",
    is_discontinued: false,
    price_in_cents: 1495,
    regular_price_in_cents: 1495,
    limited_time_offer_savings_in_cents: 0,
    limited_time_offer_ends_on: null,
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Canada, Ontario",
    product_package: "6x473 mL can",
    package_unit_type: "can",
    package_unit_volume_in_milliliters: 473,
    total_package_units: 6,
    volume_in_milliliters: 2838,
    alcohol_content: 500,
    price_per_liter_of_alcohol_in_cents: 1053,
    price_per_liter_in_cents: 526,
    inventory_count: 43286,
    inventory_volume_in_milliliters: 122845668,
    inventory_price_in_cents: 64712570,
    sugar_content: null,
    producer_name: "Molson's Brewery of Canada Limited",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: false,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion:
      "Great on its own. Will also complement grilled white meats, seafood and sausage. Of course, always great with bar snacks.",
    tasting_note:
      "Made from the very best ingredients and always preservative free. Pours a light golden colour with a soft fluffy head. Delicate floral and barley aromas with notes of citrus, grain and sweet fruit. Crisp, clean, medium bodied and smooth on the palate. Flavours of light hops, sweet malt and citrus. Pleasant hoppy finish.",
    updated_at: "2019-01-21T14:34:19.324Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/300699/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/300699/images/full.jpeg",
    varietal: "North American Lager",
    style: "Light & Malty",
    tertiary_category: "Pale Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 300699
  },
  {
    id: 696161,
    is_dead: false,
    name: "Busch",
    tags: "busch beer lager canada ontario labatt breweries can",
    is_discontinued: false,
    price_in_cents: 1175,
    regular_price_in_cents: 1275,
    limited_time_offer_savings_in_cents: 100,
    limited_time_offer_ends_on: "2019-02-03",
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Canada, Ontario",
    product_package: "6x473 mL can",
    package_unit_type: "can",
    package_unit_volume_in_milliliters: 473,
    total_package_units: 6,
    volume_in_milliliters: 2838,
    alcohol_content: 470,
    price_per_liter_of_alcohol_in_cents: 880,
    price_per_liter_in_cents: 414,
    inventory_count: 36157,
    inventory_volume_in_milliliters: 102613566,
    inventory_price_in_cents: 42484475,
    sugar_content: null,
    producer_name: "Labatt Breweries Ontario",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: true,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion:
      "Serve well chilled as a great refresher or serve with fajitas, wings or nachos.",
    tasting_note:
      "Crisp and light-bodied Busch is an American classic. It pours a clear pale straw colour, with generous foamy head. Subtle malt and toasted grain aromas, and flavours of cereal, sweet malt and a hint of sweet corn. Balanced and creamy-textured on the palate, with subtle hops on the finish. Serve ice-cold with casual cuisine.",
    updated_at: "2019-01-21T14:19:44.090Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/696161/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/696161/images/full.jpeg",
    varietal: "North American Lager",
    style: "Light & Malty",
    tertiary_category: "Pale Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 696161
  },
  {
    id: 311779,
    is_dead: false,
    name: "Bud Light",
    tags: "bud light beer lager canada ontario labatt breweries can",
    is_discontinued: false,
    price_in_cents: 1395,
    regular_price_in_cents: 1495,
    limited_time_offer_savings_in_cents: 100,
    limited_time_offer_ends_on: "2019-02-03",
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Canada, Ontario",
    product_package: "6x473 mL can",
    package_unit_type: "can",
    package_unit_volume_in_milliliters: 473,
    total_package_units: 6,
    volume_in_milliliters: 2838,
    alcohol_content: 400,
    price_per_liter_of_alcohol_in_cents: 1228,
    price_per_liter_in_cents: 491,
    inventory_count: 36106,
    inventory_volume_in_milliliters: 102468828,
    inventory_price_in_cents: 50367870,
    sugar_content: null,
    producer_name: "Labatt Breweries Ontario",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: true,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion: "Serve chilled with finger foods",
    tasting_note:
      "Light golden colour; light malt & hops; very light body touch of citrus to finish.",
    updated_at: "2019-01-21T14:19:33.893Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/311779/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/311779/images/full.jpeg",
    varietal: "Light Lager",
    style: "Light & Malty",
    tertiary_category: "Light Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 311779
  },
  {
    id: 186510,
    is_dead: false,
    name: "Corona Extra",
    tags:
      "corona extra beer lager mexico region not specified cerveceria modelo sa de cv bottle",
    is_discontinued: false,
    price_in_cents: 1450,
    regular_price_in_cents: 1450,
    limited_time_offer_savings_in_cents: 0,
    limited_time_offer_ends_on: null,
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Mexico, Region Not Specified",
    product_package: "6x330 mL bottle",
    package_unit_type: "bottle",
    package_unit_volume_in_milliliters: 330,
    total_package_units: 6,
    volume_in_milliliters: 1980,
    alcohol_content: 459,
    price_per_liter_of_alcohol_in_cents: 1595,
    price_per_liter_in_cents: 732,
    inventory_count: 42675,
    inventory_volume_in_milliliters: 84496500,
    inventory_price_in_cents: 61878750,
    sugar_content: null,
    producer_name: "Cerveceria Modelo Sa de Cv",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: false,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion: "Serve with a twist of lime; tacos or nachos",
    tasting_note:
      "Light gold colour; forward grassy hop nose; soft hop taste; light-body; softly bitter, clean finish",
    updated_at: "2019-01-21T14:23:09.466Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/186510/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/186510/images/full.jpeg",
    varietal: "North American Lager",
    style: "Light & Malty",
    tertiary_category: "Pale Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 186510
  },
  {
    id: 302810,
    is_dead: false,
    name: "Heineken",
    tags:
      "heineken beer lager netherlands region not specified heineken's heinekens brouwerijen nederland bv can",
    is_discontinued: false,
    price_in_cents: 1695,
    regular_price_in_cents: 1695,
    limited_time_offer_savings_in_cents: 0,
    limited_time_offer_ends_on: null,
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Netherlands, Region Not Specified",
    product_package: "6x500 mL can",
    package_unit_type: "can",
    package_unit_volume_in_milliliters: 500,
    total_package_units: 6,
    volume_in_milliliters: 3000,
    alcohol_content: 500,
    price_per_liter_of_alcohol_in_cents: 1130,
    price_per_liter_in_cents: 565,
    inventory_count: 25067,
    inventory_volume_in_milliliters: 75201000,
    inventory_price_in_cents: 42488565,
    sugar_content: null,
    producer_name: "Heineken's Brouwerijen Nederland BV",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: false,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion:
      "A wonderful thirst quencher. Also, a great refresher when paired with appetizers, lightly spiced dishes, pizza or burgers.",
    tasting_note:
      "142 years of tradition are behind this iconic, premium lager. Clear gold yellow colour with fine head. Appealing aromas of sweet malt, floral hops and hints of biscuit, grain and herb. Dry, crisp and fresh with a creamy texture. Flavours of barley malt and fruit, leading to grassy/herbal notes on a refreshing bitter finish.",
    updated_at: "2019-01-21T14:28:21.811Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/302810/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/302810/images/full.jpeg",
    varietal: "European Lager",
    style: "Light & Hoppy",
    tertiary_category: "Pale Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 302810
  },
  {
    id: 142620,
    is_dead: false,
    name: "Laker Ice",
    tags: "laker ice beer lager canada ontario the brick brewing co can",
    is_discontinued: false,
    price_in_cents: 215,
    regular_price_in_cents: 215,
    limited_time_offer_savings_in_cents: 0,
    limited_time_offer_ends_on: null,
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Canada, Ontario",
    product_package: "473 mL can",
    package_unit_type: "can",
    package_unit_volume_in_milliliters: 473,
    total_package_units: 1,
    volume_in_milliliters: 473,
    alcohol_content: 550,
    price_per_liter_of_alcohol_in_cents: 826,
    price_per_liter_in_cents: 454,
    inventory_count: 150819,
    inventory_volume_in_milliliters: 71337387,
    inventory_price_in_cents: 32426085,
    sugar_content: null,
    producer_name: "The Brick Brewing Co",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: false,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion:
      "Serve with grilled meats, pizza, chicken wings or mildly spicy dishes.",
    tasting_note:
      "Laker Ice is ice-brewed, resulting in a clean, smooth finish and slightly higher alcohol level. Malty notes in the foreground with moderate hops bitterness providing balance.",
    updated_at: "2019-01-21T14:31:32.693Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/142620/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/142620/images/full.jpeg",
    varietal: "Strong Lager",
    style: "Light & Hoppy",
    tertiary_category: "Strong Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 142620
  },
  {
    id: 586677,
    is_dead: false,
    name: "Old Milwaukee Ice",
    tags:
      "old milwaukee ice beer lager canada ontario sleeman brewing malting co can",
    is_discontinued: false,
    price_in_cents: 1200,
    regular_price_in_cents: 1275,
    limited_time_offer_savings_in_cents: 75,
    limited_time_offer_ends_on: "2019-02-03",
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Canada, Ontario",
    product_package: "6x473 mL can",
    package_unit_type: "can",
    package_unit_volume_in_milliliters: 473,
    total_package_units: 6,
    volume_in_milliliters: 2838,
    alcohol_content: 550,
    price_per_liter_of_alcohol_in_cents: 768,
    price_per_liter_in_cents: 422,
    inventory_count: 25008,
    inventory_volume_in_milliliters: 70972704,
    inventory_price_in_cents: 30009600,
    sugar_content: null,
    producer_name: "Sleeman Brewing & Malting Co",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: true,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion: "Serve with party mix and easy going snacks.",
    tasting_note:
      "Yellow amber; light grainy aroma; dry, slightly bitter flavour.",
    updated_at: "2019-01-21T14:35:33.486Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/586677/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/586677/images/full.jpeg",
    varietal: "North American Lager",
    style: "Light & Malty",
    tertiary_category: "Pale Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 586677
  },
  {
    id: 367938,
    is_dead: false,
    name: "Stella Artois",
    tags:
      "stella artois beer lager belgium region not specified labatt breweries ontario can",
    is_discontinued: false,
    price_in_cents: 1695,
    regular_price_in_cents: 1695,
    limited_time_offer_savings_in_cents: 0,
    limited_time_offer_ends_on: null,
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Belgium, Region Not Specified",
    product_package: "6x500 mL can",
    package_unit_type: "can",
    package_unit_volume_in_milliliters: 500,
    total_package_units: 6,
    volume_in_milliliters: 3000,
    alcohol_content: 500,
    price_per_liter_of_alcohol_in_cents: 1130,
    price_per_liter_in_cents: 565,
    inventory_count: 23566,
    inventory_volume_in_milliliters: 70698000,
    inventory_price_in_cents: 39944370,
    sugar_content: null,
    producer_name: "Labatt Breweries Ontario",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: false,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion: "Pair with fish tacos, nachos or Vienna sausage.",
    tasting_note:
      "Pale gold colour; aromas of yellow apples, toast and light floral hops; on the palate it is light-medium bodied and lightly carbonated, with flavours of fresh citrus, biscuit and light hop bitterness.",
    updated_at: "2019-01-21T14:40:31.016Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/367938/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/367938/images/full.jpeg",
    varietal: "European Lager",
    style: "Light & Malty",
    tertiary_category: "Pale Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 367938
  },
  {
    id: 18,
    is_dead: false,
    name: "Heineken",
    tags:
      "heineken beer lager netherlands region not specified heineken's heinekens brouwerijen nederland bv bottle",
    is_discontinued: false,
    price_in_cents: 1450,
    regular_price_in_cents: 1450,
    limited_time_offer_savings_in_cents: 0,
    limited_time_offer_ends_on: null,
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Netherlands, Region Not Specified",
    product_package: "6x330 mL bottle",
    package_unit_type: "bottle",
    package_unit_volume_in_milliliters: 330,
    total_package_units: 6,
    volume_in_milliliters: 1980,
    alcohol_content: 500,
    price_per_liter_of_alcohol_in_cents: 1464,
    price_per_liter_in_cents: 732,
    inventory_count: 32874,
    inventory_volume_in_milliliters: 65090520,
    inventory_price_in_cents: 47667300,
    sugar_content: null,
    producer_name: "Heineken's Brouwerijen Nederland BV",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: false,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion:
      "A wonderful thirst quencher. Also, a great refresher when paired with appetizers, lightly spiced dishes, pizza or burgers.",
    tasting_note:
      "142 years of tradition are behind this iconic, premium lager. Clear gold yellow colour with fine head. Appealing aromas of sweet malt, floral hops and hints of biscuit, grain and herb. Dry, crisp and fresh with a creamy texture. Flavours of barley malt and fruit, leading to grassy/herbal notes on a refreshing bitter finish.",
    updated_at: "2019-01-21T14:28:21.563Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/18/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/18/images/full.jpeg",
    varietal: "European Lager",
    style: "Light & Hoppy",
    tertiary_category: "Pale Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 18
  },
  {
    id: 696468,
    is_dead: false,
    name: "Labatt Blue",
    tags: "labatt blue beer lager canada ontario breweries can",
    is_discontinued: false,
    price_in_cents: 204,
    regular_price_in_cents: 220,
    limited_time_offer_savings_in_cents: 16,
    limited_time_offer_ends_on: "2019-02-03",
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Canada, Ontario",
    product_package: "473 mL can",
    package_unit_type: "can",
    package_unit_volume_in_milliliters: 473,
    total_package_units: 1,
    volume_in_milliliters: 473,
    alcohol_content: 500,
    price_per_liter_of_alcohol_in_cents: 862,
    price_per_liter_in_cents: 431,
    inventory_count: 119954,
    inventory_volume_in_milliliters: 56738242,
    inventory_price_in_cents: 24470616,
    sugar_content: null,
    producer_name: "Labatt Breweries Ontario",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: true,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion:
      "Pair with light snacks and finger foods, such as pretzels, bar nuts, chips and party mix.",
    tasting_note:
      "Labatt Blue is the world's best-selling Canadian beer, named for the colour of its label by fans of the Winnipeg Blue Bombers football team. It's fresh and crisp, with cereal grain, citrus and grassy hops notes; perfect for backyard entertaining.",
    updated_at: "2019-01-21T14:31:24.379Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/696468/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/696468/images/full.jpeg",
    varietal: "North American Lager",
    style: "Light & Malty",
    tertiary_category: "Pale Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 696468
  },
  {
    id: 487256,
    is_dead: false,
    name: "Stella Artois",
    tags:
      "stella artois beer lager belgium region not specified nvinterbrew bottle",
    is_discontinued: false,
    price_in_cents: 1475,
    regular_price_in_cents: 1475,
    limited_time_offer_savings_in_cents: 0,
    limited_time_offer_ends_on: null,
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Belgium, Region Not Specified",
    product_package: "6x330 mL bottle",
    package_unit_type: "bottle",
    package_unit_volume_in_milliliters: 330,
    total_package_units: 6,
    volume_in_milliliters: 1980,
    alcohol_content: 500,
    price_per_liter_of_alcohol_in_cents: 1489,
    price_per_liter_in_cents: 744,
    inventory_count: 28478,
    inventory_volume_in_milliliters: 56386440,
    inventory_price_in_cents: 42005050,
    sugar_content: null,
    producer_name: "N.V.INTERBREW. Belgium",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: false,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion: "Pair with fish tacos, nachos or Vienna sausage.",
    tasting_note:
      "Pale gold colour; aromas of yellow apples, toast and light floral hops; on the palate it is light-medium bodied and lightly carbonated, with flavours of fresh citrus, biscuit and light hop bitterness.",
    updated_at: "2019-01-21T14:40:30.777Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/487256/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/487256/images/full.jpeg",
    varietal: "European Lager",
    style: "Light & Malty",
    tertiary_category: "Pale Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 487256
  },
  {
    id: 535294,
    is_dead: false,
    name: "Grolsch Premium Lager",
    tags:
      "grolsch premium lager beer netherlands region not specified grolsche bierbrouwerij bv can",
    is_discontinued: false,
    price_in_cents: 254,
    regular_price_in_cents: 254,
    limited_time_offer_savings_in_cents: 0,
    limited_time_offer_ends_on: null,
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Netherlands, Region Not Specified",
    product_package: "500 mL can",
    package_unit_type: "can",
    package_unit_volume_in_milliliters: 500,
    total_package_units: 1,
    volume_in_milliliters: 500,
    alcohol_content: 500,
    price_per_liter_of_alcohol_in_cents: 1016,
    price_per_liter_in_cents: 508,
    inventory_count: 97670,
    inventory_volume_in_milliliters: 48835000,
    inventory_price_in_cents: 24808180,
    sugar_content: null,
    producer_name: "Grolsche Bierbrouwerij B.V.",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: false,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion: "grilled sausages, schnitzel, potato salad",
    tasting_note:
      "Medium gold colour; rich grain and hop aromas with hints of spice; rich, smooth and balanced with refreshing hoppy character",
    updated_at: "2019-01-21T14:27:58.013Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/535294/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/535294/images/full.jpeg",
    varietal: "European Lager",
    style: "Medium & Hoppy",
    tertiary_category: "Pale Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 535294
  },
  {
    id: 905976,
    is_dead: false,
    name: "Budweiser",
    tags: "budweiser beer lager canada ontario labatt breweries can",
    is_discontinued: false,
    price_in_cents: 260,
    regular_price_in_cents: 260,
    limited_time_offer_savings_in_cents: 0,
    limited_time_offer_ends_on: null,
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Canada, Ontario",
    product_package: "473 mL can",
    package_unit_type: "can",
    package_unit_volume_in_milliliters: 473,
    total_package_units: 1,
    volume_in_milliliters: 473,
    alcohol_content: 500,
    price_per_liter_of_alcohol_in_cents: 1099,
    price_per_liter_in_cents: 549,
    inventory_count: 100697,
    inventory_volume_in_milliliters: 47629681,
    inventory_price_in_cents: 26181220,
    sugar_content: null,
    producer_name: "Labatt Breweries Ontario",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: false,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion: null,
    tasting_note: null,
    updated_at: "2019-01-21T14:19:36.231Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/905976/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/905976/images/full.jpeg",
    varietal: "North American Lager",
    style: "Light & Malty",
    tertiary_category: "Pale Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 905976
  },
  {
    id: 921478,
    is_dead: false,
    name: "Pabst Blue Ribbon",
    tags:
      "pabst blue ribbon beer lager canada ontario sleeman brewing malting co can",
    is_discontinued: false,
    price_in_cents: 944,
    regular_price_in_cents: 994,
    limited_time_offer_savings_in_cents: 50,
    limited_time_offer_ends_on: "2019-02-03",
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Canada, Ontario",
    product_package: "6x355 mL can",
    package_unit_type: "can",
    package_unit_volume_in_milliliters: 355,
    total_package_units: 6,
    volume_in_milliliters: 2130,
    alcohol_content: 500,
    price_per_liter_of_alcohol_in_cents: 886,
    price_per_liter_in_cents: 443,
    inventory_count: 21602,
    inventory_volume_in_milliliters: 46012260,
    inventory_price_in_cents: 20392288,
    sugar_content: null,
    producer_name: "Sleeman Brewing & Malting Co",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: true,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion:
      "Pair with easy-going snacks like hot dogs, chips or even late night poutine.",
    tasting_note:
      "Very pale golden colour with frothy mousse; delicate malt aromas with hints of banana and pear fruit; medium-light bodied with clean flavours of cereal and light hops on the finish.",
    updated_at: "2019-01-21T14:35:50.579Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/921478/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/921478/images/full.jpeg",
    varietal: "North American Lager",
    style: "Light & Malty",
    tertiary_category: "Pale Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 921478
  },
  {
    id: 254946,
    is_dead: false,
    name: "Dab Original",
    tags:
      "dab original beer lager germany region not specified dortmunder actien brauerei kg can",
    is_discontinued: false,
    price_in_cents: 210,
    regular_price_in_cents: 210,
    limited_time_offer_savings_in_cents: 0,
    limited_time_offer_ends_on: null,
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Germany, Region Not Specified",
    product_package: "500 mL can",
    package_unit_type: "can",
    package_unit_volume_in_milliliters: 500,
    total_package_units: 1,
    volume_in_milliliters: 500,
    alcohol_content: 500,
    price_per_liter_of_alcohol_in_cents: 840,
    price_per_liter_in_cents: 420,
    inventory_count: 91531,
    inventory_volume_in_milliliters: 45765500,
    inventory_price_in_cents: 19221510,
    sugar_content: null,
    producer_name: "Dortmunder Actien Brauerei Kg",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: false,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion: "Enjoy with battered fish, calamari or burgers.",
    tasting_note:
      "Pale lemon in colour with a frothy mousse; soft grain, light hops and malt on the nose; dry and medium body with a creamy texture.",
    updated_at: "2019-01-21T14:23:40.765Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/254946/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/254946/images/full.jpeg",
    varietal: "European Lager",
    style: "Light & Floral",
    tertiary_category: "Pale Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 254946
  },
  {
    id: 493916,
    is_dead: false,
    name: "Old Milwaukee",
    tags:
      "old milwaukee beer lager canada ontario sleeman brewing malting co can",
    is_discontinued: false,
    price_in_cents: 1275,
    regular_price_in_cents: 1275,
    limited_time_offer_savings_in_cents: 0,
    limited_time_offer_ends_on: null,
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Canada, Ontario",
    product_package: "6x473 mL can",
    package_unit_type: "can",
    package_unit_volume_in_milliliters: 473,
    total_package_units: 6,
    volume_in_milliliters: 2838,
    alcohol_content: 490,
    price_per_liter_of_alcohol_in_cents: 916,
    price_per_liter_in_cents: 449,
    inventory_count: 15512,
    inventory_volume_in_milliliters: 44023056,
    inventory_price_in_cents: 19777800,
    sugar_content: null,
    producer_name: "Sleeman Brewing & Malting Co",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: false,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion: "Roadhouse Fare",
    tasting_note:
      "Pale straw colour, soft, light, sweetish aromas of grain, light bodied and mild on the palate.",
    updated_at: "2019-01-21T14:35:32.898Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/493916/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/493916/images/full.jpeg",
    varietal: "North American Lager",
    style: "Light & Malty",
    tertiary_category: "Pale Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 493916
  },
  {
    id: 488411,
    is_dead: false,
    name: "Carling",
    tags:
      "carling beer lager canada ontario molson's molsons brewery of limited can",
    is_discontinued: false,
    price_in_cents: 1195,
    regular_price_in_cents: 1275,
    limited_time_offer_savings_in_cents: 80,
    limited_time_offer_ends_on: "2019-02-03",
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Canada, Ontario",
    product_package: "6x473 mL can",
    package_unit_type: "can",
    package_unit_volume_in_milliliters: 473,
    total_package_units: 6,
    volume_in_milliliters: 2838,
    alcohol_content: 490,
    price_per_liter_of_alcohol_in_cents: 859,
    price_per_liter_in_cents: 421,
    inventory_count: 15064,
    inventory_volume_in_milliliters: 42751632,
    inventory_price_in_cents: 18001480,
    sugar_content: null,
    producer_name: "Molson's Brewery of Canada Limited",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: true,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion:
      "Pair this with salty appetizers, honey roasted peanuts or party mix.",
    tasting_note:
      "Pale straw colour with a fine mousse; a light and malty nose; sweet malty flavours with a clean finish.",
    updated_at: "2019-01-21T14:20:15.410Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/488411/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/488411/images/full.jpeg",
    varietal: "North American Lager",
    style: "Light & Malty",
    tertiary_category: "Pale Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 488411
  },
  {
    id: 908640,
    is_dead: false,
    name: "Bud Light",
    tags: "bud light beer lager canada ontario labatt breweries can",
    is_discontinued: false,
    price_in_cents: 4495,
    regular_price_in_cents: 4495,
    limited_time_offer_savings_in_cents: 0,
    limited_time_offer_ends_on: null,
    bonus_reward_miles: 0,
    bonus_reward_miles_ends_on: null,
    stock_type: "LCBO",
    primary_category: "Beer",
    secondary_category: "Lager",
    origin: "Canada, Ontario",
    product_package: "24x355 mL can",
    package_unit_type: "can",
    package_unit_volume_in_milliliters: 355,
    total_package_units: 24,
    volume_in_milliliters: 8520,
    alcohol_content: 400,
    price_per_liter_of_alcohol_in_cents: 1318,
    price_per_liter_in_cents: 527,
    inventory_count: 4925,
    inventory_volume_in_milliliters: 41961000,
    inventory_price_in_cents: 22137875,
    sugar_content: null,
    producer_name: "Labatt Breweries Ontario",
    released_on: null,
    has_value_added_promotion: false,
    has_limited_time_offer: false,
    has_bonus_reward_miles: false,
    is_seasonal: false,
    is_vqa: false,
    is_ocb: false,
    is_kosher: false,
    value_added_promotion_description: null,
    description: null,
    serving_suggestion: "Serve chilled with finger foods",
    tasting_note:
      "Light golden colour; light malt & hops; very light body touch of citrus to finish.",
    updated_at: "2019-01-21T14:19:34.567Z",
    image_thumb_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/908640/images/thumb.png",
    image_url:
      "https://dx5vpyka4lqst.cloudfront.net/products/908640/images/full.jpeg",
    varietal: "Light Lager",
    style: "Light & Malty",
    tertiary_category: "Light Lager",
    sugar_in_grams_per_liter: null,
    clearance_sale_savings_in_cents: 0,
    has_clearance_sale: false,
    product_no: 908640
  }
]
